export const LIQUID_PARAMS = {
  nav: {
    displacementScale: 45,
    blurAmount: 0.1,
    saturation: 130,
    aberrationIntensity: 2,
    elasticity: 0,
    cornerRadius: 100,
    mode: "standard",
    overLight: false,
  },
  communityModal: {
    displacementScale: 37,
    blurAmount: 0.1,
    saturation: 116,
    aberrationIntensity: 4.8,
    elasticity: 0.3,
    cornerRadius: 20,
    mode: "prominent",
    overLight: false,
  },
  playButton: {
    displacementScale: 60,
    blurAmount: 0.08,
    saturation: 110,
    aberrationIntensity: 2.5,
    elasticity: 0.25,
    cornerRadius: 999,
    mode: "standard",
    overLight: false,
  },
  tabHighlight: {
    opacity: 0.5,
    blurAmount: 5,
    saturation: 100,
    tintOpacity: 0.04,
    borderOpacity: 0.18,
    innerHighlightOpacity: 0.18,
    cornerRadius: 999,
    shadowOpacity: 0.08,
  },
};
